### ISSUE TITLE
Doesn’t compile

### ISSUE THREAD

**Issue by zhm** [cookiemccormick/learn-co-sandbox#1]
I’m having trouble getting this project to work

**Comment by cookiemccormick** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/757ac79c-3669-42d3-b687-13e66b9ff56f-e7700139-6873-4c56-ad34-f7fb0599500b-v1.png?transparent=1&palette=1&width=246)

**Comment by zhm** [comment]
Any update on this?
